# Generated by Django 6.0.3 on 2026-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
